default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: rails_warden_sample_development

test:
  <<: *default
  database: rails_warden_sample_test
